### ISSUE TITLE
easyWave run instructions is out of date

### ISSUE THREAD

**Issue by Naghasan** [oneapi-src/Velocity-Bench#1]
Hi

The easywave run instructions point to non existing data in the repo and I can't find instruction on where to get it. Could you update the readme with instructions on how to get them ?

Thanks

Note: the link to the original source is dead.

**Comment by jgtong** [comment]
@Naghasan , Thanks for pointing this out. Please take a look here https://github.com/oneapi-src/Velocity-Bench/blob/main/easywave/README.md

**Comment by Naghasan** [comment]
Hi @jgtong 

thanks for fixing the link, but I do not see any instruction on how to get the test data (e.g. where do I get `BengkuluSept2007.flt` and `e2Asean.grid`)

**Comment by jgtong** [comment]
@Naghasan 

The data files can be downloaded here, which is from the original CUDA repository: https://git.gfz-potsdam.de/id2/geoperil/easyWave/-/tree/master/data 

I will update the ReadMe accordingly. 

Thank you
