### ISSUE TITLE
lc0 dependencies is not accessible 

### ISSUE THREAD

**Issue by Naghasan** [oneapi-src/Velocity-Bench#2]
Hi

The readme of `lc0`, mentions the required dependency `752187.pb.gz`, however you need to be able to access the intel's sharepoint in order to get it. Link points to https://intel.sharepoint.com/:u:/r/sites/onebench/Shared%20Documents/Data%20Files/lc0_data.zip?csf=1&web=1&e=aSHNvO

**Comment by KateBlueSky** [comment]
Hi, it's available lc0 Release v0.28-rc2 as the default network.. If you download the  [lc0-v0.28.0-rc2-windows-gpu-nvidia-cuda.zip](https://github.com/LeelaChessZero/lc0/releases/download/v0.28.0-rc2/lc0-v0.28.0-rc2-windows-gpu-nvidia-cuda.zip). In the zip you'll find a 752187.pb.gz
