### ISSUE TITLE
cudaSift verification fails when not unrolling

### ISSUE THREAD

**Issue by victor-eds** [oneapi-src/Velocity-Bench#28]
When [the `pragma unroll` directive in `LowPassBlockOld`](https://github.com/oneapi-src/Velocity-Bench/blob/a357dbdb8aa1dca9e1b6be40542e394655b0f3a2/cudaSift/SYCL/cudaSiftD.dp.cpp#L1159) is not applied, e.g., if it is commented out, verification for `cudaSift` fails. This should not be happening, as unrolling's an optimization and should not affect program semantics.

Using `LowPassBlock` with no unrolling is working fine.

## Possible solutions

Unless considerable performance improvements yield from using `LowPassBlockOld`, switch to `LowPassBlock` ([here](https://github.com/oneapi-src/Velocity-Bench/blob/a357dbdb8aa1dca9e1b6be40542e394655b0f3a2/cudaSift/SYCL/cudaSiftH.dp.cpp#L682C1-L682C43)).

## Environment

`icpx`: `2023.2.0.20230721`
Device name: Intel(R) UHD Graphics 630
`intel-level-zero-gpu`: `1.3.26690.36-704`
`intel-igc`: `1.0.14062.11`
OS: `Ubuntu 22.04.3 LTS`
Linux Kernel: `6.2.0-32`

**Comment by skambapugithub** [comment]
Currently reproducing the issue on our end.
Will come back with any further updates.
Thanks @victor-eds

**Comment by skambapugithub** [comment]
Used LowPassBlock function instead of LowPassBlockOld to fix the issue. 
Closing this issue.
Thanks .
