### ISSUE TITLE
tsne update

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/Velocity-Bench#44]
Hi,

I updated the tsne examples. Thanks for your review.

https://github.com/zjin-lcf/HeCBench/commit/ab8697b4d1c7f8ea78f56f1b7c9b3dc7b5a454ec

**Comment by mgrabban** [comment]
Hello,

You made a lot of changes. Can you please provide details regarding them?

Thanks.

**Comment by mgrabban** [comment]
Hello @zjin-lcf,

I did not get any details. Please let me know if you still need help here otherwise I want to close this issue. thanks.

**Comment by zjin-lcf** [comment]
I will close the issue.
