### ISSUE TITLE
SVM Verification Failure on SYCL for Nvidia Backend

### ISSUE THREAD

**Issue by cl-bautch** [oneapi-src/Velocity-Bench#62]
When running the SVM benchmark on SYCL for Nvidia backend, the program fails verification with the following output:

```
Number of args 3
Using cuSVM (Carpenter)...

Buffering input text file (6989624 B).
Load Done
Starting Training
_C 1.000000
Workgroup Size: 1024
nbrCtas 80
elemsPerCta 1248
threadsPerCta 128
Total run time: 0.205239 seconds
Iter:100
M:97683
N:123
Train done. Calulate Vector counts
Training done

Loading    elapsed time : 0.0753 s
Processing elapsed time : 0.2141 s
Storing    elapsed time : 0.0007 s
Total      elapsed time : 0.2901 s
Result's are incorrect : -0.8917
```

For comparison, this is the output I get when running the CUDA version of this benchmark, which passes verification:

```
Using cuSVM (Carpenter)...

Buffering input text file (6989624 B).
Starting Training
_C 1.000000
Total run time: 0.218892 seconds
Iter:100
M:97683
N:123
Train done. Calulate Vector counts.

Loading    elapsed time : 0.0767 s
Processing elapsed time : 0.2861 s
Storing    elapsed time : 0.0013 s
Total      elapsed time : 0.3641 s
Result's are correct: 0.0551
```

I am compiling it using icpx rather than clang++ (which hasn't given me issues for most of the other benchmarks) but otherwise following the README instructions exactly.

```
CC=icpx CXX=icpx cmake -DUSE_NVIDIA_BACKEND=TRUE -DUSE_SM=86 ../
```

## Environment

icpx: 2024.0.0.20231017
CUDA: 12.4
Driver: 550.90.07
Device: NVIDIA RTX A5000 (SM=86) [Also tested on NVIDIA L40 to identical results]

**Comment by KateBlueSky** [comment]
The interop calls to the cuBlas libraries need to be updated in the workload. I'll update it on a development branch and open a PR for it.

**Comment by KateBlueSky** [comment]
#64
