### ISSUE TITLE
cudaSift SYCL uses removed API

### ISSUE THREAD

**Issue by pbalcer** [oneapi-src/Velocity-Bench#68]
https://github.com/oneapi-src/Velocity-Bench/blob/7e440b794faac36e1bfd33831c021626e614b936/cudaSift/SYCL/infra/device.hpp#L208

`is_host()` has been long deprecated and the latest SYCLOS compiler removed it. See https://github.com/intel/llvm/pull/14258.

For my use, I simply removed the entire condition: https://github.com/pbalcer/Velocity-Bench/commit/39ea36e70533a968526fcd25c3f233b0a6d0412a

**Comment by rmukhopa** [comment]
Same comment, as for #69
