### ISSUE TITLE
QuickSilver SYCL uses removed APIs

### ISSUE THREAD

**Issue by pbalcer** [oneapi-src/Velocity-Bench#69]
Just like in #68, QuickSilver uses APIs that are now long deprecated and no longer exist in SYCLOS.
See my changes here: https://github.com/pbalcer/Velocity-Bench/commit/ae0ae05c7fd1469779ecea4f36e4741b1d956eb4

I can make a PR if simply removing the use of those APIs is good enough (like I did on my fork).

**Comment by rmukhopa** [comment]
@pbalcer - thanks for creating this issue. We are in the midst of making changes and you should see a PR soon.
