### ISSUE TITLE
Hardcoded relative path in cudaSift

### ISSUE THREAD

**Issue by pbalcer** [oneapi-src/Velocity-Bench#73]
The cudaSift benchmark currently hardcodes a relative path to its assets. See [here](https://github.com/oneapi-src/Velocity-Bench/blob/main/cudaSift/SYCL/mainSift.cpp#L94). This works fine as long as the benchmark is ran from `repo/cudaSift/SYCL/build/` directory, but breaks down when the benchmark is built outside of the repository or when the current working directory is simply set to somewhere else.
This has forced me to do a [workaround ](https://github.com/oneapi-src/unified-runtime/pull/1902/files#diff-da75386a9ed5f33895c2cd693fc250066bf1c6423977015dd65436f9d7857ac3R75-R77) in my automation that artificially introduces an extraneous directory into the benchmark cwd that my scripts use, just so that those files can be resolved appropriately.

It would be better if the path to those files could be provider as a cli argument.

**Comment by skambapugithub** [comment]
As the input files are shipped with the application, we used a relative path to where the input files are located.
Will soon update the code to pass in input file location via CLI argument.

**Comment by rmukhopa** [comment]
Hi @pbalcer, we have made changes to address this issue. It is currently under validation and once all goes well, we will raise a PR here.

**Comment by rmukhopa** [comment]
Hi @pbalcer, PR for this issue is #74.   

To specify a different dir for the input files, you will now have to pass that in as a command line parameter:
./cudasift -input_data_loc <INPUT_FILES_DIR>

**Comment by rmukhopa** [comment]
The PR is now merged. I hope it addressed your issue adequately? If not, please let me know. Thanks.

**Comment by rmukhopa** [comment]
@pbalcer, if this ticket addressed the issue at hand, please let me know so that this issue can be closed.

**Comment by pbalcer** [comment]
Yes, thanks!
